version: '3.8'

services:
  # Development environment with hot-reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"     # Express server
      - "5173:5173"     # Vite dev server
    volumes:
      - ./client/src:/app/client/src
      - ./server:/app/server
      - ./shared:/app/shared
    environment:
      - NODE_ENV=development
      - SKIP_EXCEL_IMPORT=true
      - CHOKIDAR_USEPOLLING=true  # For hot-reload in Docker
    networks:
      - app-network

  # Production environment
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - app-network
    depends_on:
      - postgres

  # PostgreSQL database (optional)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: internetproviders
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: internetproviders
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  # Adminer for database management (optional)
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: